// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/config/android/network_trace_config.proto

#include "protos/perfetto/config/android/network_trace_config.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace perfetto {
namespace protos {
template <typename>
PROTOBUF_CONSTEXPR NetworkPacketTraceConfig::NetworkPacketTraceConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.poll_ms_)*/ 0u

  , /*decltype(_impl_.aggregation_threshold_)*/ 0u

  , /*decltype(_impl_.intern_limit_)*/ 0u

  , /*decltype(_impl_.drop_local_port_)*/ false

  , /*decltype(_impl_.drop_remote_port_)*/ false

  , /*decltype(_impl_.drop_tcp_flags_)*/ false
} {}
struct NetworkPacketTraceConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NetworkPacketTraceConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NetworkPacketTraceConfigDefaultTypeInternal() {}
  union {
    NetworkPacketTraceConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NetworkPacketTraceConfigDefaultTypeInternal _NetworkPacketTraceConfig_default_instance_;
}  // namespace protos
}  // namespace perfetto
static ::_pb::Metadata file_level_metadata_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto = nullptr;
const ::uint32_t TableStruct_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::NetworkPacketTraceConfig, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::NetworkPacketTraceConfig, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::NetworkPacketTraceConfig, _impl_.poll_ms_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::NetworkPacketTraceConfig, _impl_.aggregation_threshold_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::NetworkPacketTraceConfig, _impl_.intern_limit_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::NetworkPacketTraceConfig, _impl_.drop_local_port_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::NetworkPacketTraceConfig, _impl_.drop_remote_port_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::NetworkPacketTraceConfig, _impl_.drop_tcp_flags_),
    0,
    1,
    2,
    3,
    4,
    5,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 14, -1, sizeof(::perfetto::protos::NetworkPacketTraceConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::perfetto::protos::_NetworkPacketTraceConfig_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n9protos/perfetto/config/android/network"
    "_trace_config.proto\022\017perfetto.protos\"\253\001\n"
    "\030NetworkPacketTraceConfig\022\017\n\007poll_ms\030\001 \001"
    "(\r\022\035\n\025aggregation_threshold\030\002 \001(\r\022\024\n\014int"
    "ern_limit\030\003 \001(\r\022\027\n\017drop_local_port\030\004 \001(\010"
    "\022\030\n\020drop_remote_port\030\005 \001(\010\022\026\n\016drop_tcp_f"
    "lags\030\006 \001(\010"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto = {
    false,
    false,
    250,
    descriptor_table_protodef_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto,
    "protos/perfetto/config/android/network_trace_config.proto",
    &descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto::offsets,
    file_level_metadata_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto,
    file_level_enum_descriptors_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto_getter() {
  return &descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto(&descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto);
namespace perfetto {
namespace protos {
// ===================================================================

class NetworkPacketTraceConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<NetworkPacketTraceConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(NetworkPacketTraceConfig, _impl_._has_bits_);
  static void set_has_poll_ms(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_aggregation_threshold(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_intern_limit(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_drop_local_port(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_drop_remote_port(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_drop_tcp_flags(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
};

NetworkPacketTraceConfig::NetworkPacketTraceConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.NetworkPacketTraceConfig)
}
NetworkPacketTraceConfig::NetworkPacketTraceConfig(const NetworkPacketTraceConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:perfetto.protos.NetworkPacketTraceConfig)
}

inline void NetworkPacketTraceConfig::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.poll_ms_) { 0u }

    , decltype(_impl_.aggregation_threshold_) { 0u }

    , decltype(_impl_.intern_limit_) { 0u }

    , decltype(_impl_.drop_local_port_) { false }

    , decltype(_impl_.drop_remote_port_) { false }

    , decltype(_impl_.drop_tcp_flags_) { false }

  };
}

NetworkPacketTraceConfig::~NetworkPacketTraceConfig() {
  // @@protoc_insertion_point(destructor:perfetto.protos.NetworkPacketTraceConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NetworkPacketTraceConfig::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void NetworkPacketTraceConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void NetworkPacketTraceConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.NetworkPacketTraceConfig)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    ::memset(&_impl_.poll_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.drop_tcp_flags_) -
        reinterpret_cast<char*>(&_impl_.poll_ms_)) + sizeof(_impl_.drop_tcp_flags_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NetworkPacketTraceConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 poll_ms = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_poll_ms(&has_bits);
          _impl_.poll_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 aggregation_threshold = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_aggregation_threshold(&has_bits);
          _impl_.aggregation_threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 intern_limit = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _Internal::set_has_intern_limit(&has_bits);
          _impl_.intern_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional bool drop_local_port = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 32)) {
          _Internal::set_has_drop_local_port(&has_bits);
          _impl_.drop_local_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional bool drop_remote_port = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 40)) {
          _Internal::set_has_drop_remote_port(&has_bits);
          _impl_.drop_remote_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional bool drop_tcp_flags = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 48)) {
          _Internal::set_has_drop_tcp_flags(&has_bits);
          _impl_.drop_tcp_flags_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* NetworkPacketTraceConfig::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.NetworkPacketTraceConfig)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 poll_ms = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_poll_ms(), target);
  }

  // optional uint32 aggregation_threshold = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_aggregation_threshold(), target);
  }

  // optional uint32 intern_limit = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_intern_limit(), target);
  }

  // optional bool drop_local_port = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this->_internal_drop_local_port(), target);
  }

  // optional bool drop_remote_port = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        5, this->_internal_drop_remote_port(), target);
  }

  // optional bool drop_tcp_flags = 6;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        6, this->_internal_drop_tcp_flags(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.NetworkPacketTraceConfig)
  return target;
}

::size_t NetworkPacketTraceConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:perfetto.protos.NetworkPacketTraceConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional uint32 poll_ms = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_poll_ms());
    }

    // optional uint32 aggregation_threshold = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_aggregation_threshold());
    }

    // optional uint32 intern_limit = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_intern_limit());
    }

    // optional bool drop_local_port = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 2;
    }

    // optional bool drop_remote_port = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 2;
    }

    // optional bool drop_tcp_flags = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 2;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NetworkPacketTraceConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    NetworkPacketTraceConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NetworkPacketTraceConfig::GetClassData() const { return &_class_data_; }


void NetworkPacketTraceConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<NetworkPacketTraceConfig*>(&to_msg);
  auto& from = static_cast<const NetworkPacketTraceConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.NetworkPacketTraceConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.poll_ms_ = from._impl_.poll_ms_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.aggregation_threshold_ = from._impl_.aggregation_threshold_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.intern_limit_ = from._impl_.intern_limit_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.drop_local_port_ = from._impl_.drop_local_port_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.drop_remote_port_ = from._impl_.drop_remote_port_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.drop_tcp_flags_ = from._impl_.drop_tcp_flags_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NetworkPacketTraceConfig::CopyFrom(const NetworkPacketTraceConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.NetworkPacketTraceConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetworkPacketTraceConfig::IsInitialized() const {
  return true;
}

void NetworkPacketTraceConfig::InternalSwap(NetworkPacketTraceConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NetworkPacketTraceConfig, _impl_.drop_tcp_flags_)
      + sizeof(NetworkPacketTraceConfig::_impl_.drop_tcp_flags_)
      - PROTOBUF_FIELD_OFFSET(NetworkPacketTraceConfig, _impl_.poll_ms_)>(
          reinterpret_cast<char*>(&_impl_.poll_ms_),
          reinterpret_cast<char*>(&other->_impl_.poll_ms_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkPacketTraceConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto_getter, &descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto_once,
      file_level_metadata_protos_2fperfetto_2fconfig_2fandroid_2fnetwork_5ftrace_5fconfig_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::perfetto::protos::NetworkPacketTraceConfig*
Arena::CreateMaybeMessage< ::perfetto::protos::NetworkPacketTraceConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::perfetto::protos::NetworkPacketTraceConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
