// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/track_event/chrome_window_handle_event_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protos_2fperfetto_2ftrace_2ftrack_5fevent_2fchrome_5fwindow_5fhandle_5fevent_5finfo_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_protos_2fperfetto_2ftrace_2ftrack_5fevent_2fchrome_5fwindow_5fhandle_5fevent_5finfo_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protos_2fperfetto_2ftrace_2ftrack_5fevent_2fchrome_5fwindow_5fhandle_5fevent_5finfo_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fperfetto_2ftrace_2ftrack_5fevent_2fchrome_5fwindow_5fhandle_5fevent_5finfo_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_protos_2fperfetto_2ftrace_2ftrack_5fevent_2fchrome_5fwindow_5fhandle_5fevent_5finfo_2eproto;
namespace perfetto {
namespace protos {
class ChromeWindowHandleEventInfo;
struct ChromeWindowHandleEventInfoDefaultTypeInternal;
extern ChromeWindowHandleEventInfoDefaultTypeInternal _ChromeWindowHandleEventInfo_default_instance_;
}  // namespace protos
}  // namespace perfetto
PROTOBUF_NAMESPACE_OPEN
template <>
::perfetto::protos::ChromeWindowHandleEventInfo* Arena::CreateMaybeMessage<::perfetto::protos::ChromeWindowHandleEventInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace perfetto {
namespace protos {

// ===================================================================


// -------------------------------------------------------------------

class ChromeWindowHandleEventInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:perfetto.protos.ChromeWindowHandleEventInfo) */ {
 public:
  inline ChromeWindowHandleEventInfo() : ChromeWindowHandleEventInfo(nullptr) {}
  ~ChromeWindowHandleEventInfo() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ChromeWindowHandleEventInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChromeWindowHandleEventInfo(const ChromeWindowHandleEventInfo& from);
  ChromeWindowHandleEventInfo(ChromeWindowHandleEventInfo&& from) noexcept
    : ChromeWindowHandleEventInfo() {
    *this = ::std::move(from);
  }

  inline ChromeWindowHandleEventInfo& operator=(const ChromeWindowHandleEventInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChromeWindowHandleEventInfo& operator=(ChromeWindowHandleEventInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChromeWindowHandleEventInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChromeWindowHandleEventInfo* internal_default_instance() {
    return reinterpret_cast<const ChromeWindowHandleEventInfo*>(
               &_ChromeWindowHandleEventInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChromeWindowHandleEventInfo& a, ChromeWindowHandleEventInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ChromeWindowHandleEventInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChromeWindowHandleEventInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChromeWindowHandleEventInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChromeWindowHandleEventInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChromeWindowHandleEventInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChromeWindowHandleEventInfo& from) {
    ChromeWindowHandleEventInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChromeWindowHandleEventInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "perfetto.protos.ChromeWindowHandleEventInfo";
  }
  protected:
  explicit ChromeWindowHandleEventInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDpiFieldNumber = 1,
    kMessageIdFieldNumber = 2,
    kHwndPtrFieldNumber = 3,
  };
  // optional uint32 dpi = 1;
  bool has_dpi() const;
  void clear_dpi() ;
  ::uint32_t dpi() const;
  void set_dpi(::uint32_t value);

  private:
  ::uint32_t _internal_dpi() const;
  void _internal_set_dpi(::uint32_t value);

  public:
  // optional uint32 message_id = 2;
  bool has_message_id() const;
  void clear_message_id() ;
  ::uint32_t message_id() const;
  void set_message_id(::uint32_t value);

  private:
  ::uint32_t _internal_message_id() const;
  void _internal_set_message_id(::uint32_t value);

  public:
  // optional fixed64 hwnd_ptr = 3;
  bool has_hwnd_ptr() const;
  void clear_hwnd_ptr() ;
  ::uint64_t hwnd_ptr() const;
  void set_hwnd_ptr(::uint64_t value);

  private:
  ::uint64_t _internal_hwnd_ptr() const;
  void _internal_set_hwnd_ptr(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:perfetto.protos.ChromeWindowHandleEventInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::uint32_t dpi_;
    ::uint32_t message_id_;
    ::uint64_t hwnd_ptr_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fperfetto_2ftrace_2ftrack_5fevent_2fchrome_5fwindow_5fhandle_5fevent_5finfo_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ChromeWindowHandleEventInfo

// optional uint32 dpi = 1;
inline bool ChromeWindowHandleEventInfo::has_dpi() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ChromeWindowHandleEventInfo::clear_dpi() {
  _impl_.dpi_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t ChromeWindowHandleEventInfo::dpi() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.ChromeWindowHandleEventInfo.dpi)
  return _internal_dpi();
}
inline void ChromeWindowHandleEventInfo::set_dpi(::uint32_t value) {
  _internal_set_dpi(value);
  // @@protoc_insertion_point(field_set:perfetto.protos.ChromeWindowHandleEventInfo.dpi)
}
inline ::uint32_t ChromeWindowHandleEventInfo::_internal_dpi() const {
  return _impl_.dpi_;
}
inline void ChromeWindowHandleEventInfo::_internal_set_dpi(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.dpi_ = value;
}

// optional uint32 message_id = 2;
inline bool ChromeWindowHandleEventInfo::has_message_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ChromeWindowHandleEventInfo::clear_message_id() {
  _impl_.message_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t ChromeWindowHandleEventInfo::message_id() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.ChromeWindowHandleEventInfo.message_id)
  return _internal_message_id();
}
inline void ChromeWindowHandleEventInfo::set_message_id(::uint32_t value) {
  _internal_set_message_id(value);
  // @@protoc_insertion_point(field_set:perfetto.protos.ChromeWindowHandleEventInfo.message_id)
}
inline ::uint32_t ChromeWindowHandleEventInfo::_internal_message_id() const {
  return _impl_.message_id_;
}
inline void ChromeWindowHandleEventInfo::_internal_set_message_id(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.message_id_ = value;
}

// optional fixed64 hwnd_ptr = 3;
inline bool ChromeWindowHandleEventInfo::has_hwnd_ptr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ChromeWindowHandleEventInfo::clear_hwnd_ptr() {
  _impl_.hwnd_ptr_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint64_t ChromeWindowHandleEventInfo::hwnd_ptr() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.ChromeWindowHandleEventInfo.hwnd_ptr)
  return _internal_hwnd_ptr();
}
inline void ChromeWindowHandleEventInfo::set_hwnd_ptr(::uint64_t value) {
  _internal_set_hwnd_ptr(value);
  // @@protoc_insertion_point(field_set:perfetto.protos.ChromeWindowHandleEventInfo.hwnd_ptr)
}
inline ::uint64_t ChromeWindowHandleEventInfo::_internal_hwnd_ptr() const {
  return _impl_.hwnd_ptr_;
}
inline void ChromeWindowHandleEventInfo::_internal_set_hwnd_ptr(::uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.hwnd_ptr_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_protos_2fperfetto_2ftrace_2ftrack_5fevent_2fchrome_5fwindow_5fhandle_5fevent_5finfo_2eproto_2epb_2eh
