// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/gpu/gpu_counter_event.proto

#include "protos/perfetto/trace/gpu/gpu_counter_event.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace perfetto {
namespace protos {
template <typename>
PROTOBUF_CONSTEXPR GpuCounterEvent_GpuCounter::GpuCounterEvent_GpuCounter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.counter_id_)*/ 0u

  , /*decltype(_impl_.value_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct GpuCounterEvent_GpuCounterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GpuCounterEvent_GpuCounterDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GpuCounterEvent_GpuCounterDefaultTypeInternal() {}
  union {
    GpuCounterEvent_GpuCounter _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GpuCounterEvent_GpuCounterDefaultTypeInternal _GpuCounterEvent_GpuCounter_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR GpuCounterEvent::GpuCounterEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.counters_)*/{}
  , /*decltype(_impl_.counter_descriptor_)*/nullptr
  , /*decltype(_impl_.gpu_id_)*/ 0
} {}
struct GpuCounterEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GpuCounterEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GpuCounterEventDefaultTypeInternal() {}
  union {
    GpuCounterEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GpuCounterEventDefaultTypeInternal _GpuCounterEvent_default_instance_;
}  // namespace protos
}  // namespace perfetto
static ::_pb::Metadata file_level_metadata_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto = nullptr;
const ::uint32_t TableStruct_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent_GpuCounter, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent_GpuCounter, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent_GpuCounter, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent_GpuCounter, _impl_.counter_id_),
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent_GpuCounter, _impl_.value_),
    0,
    ~0u,
    ~0u,
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent, _impl_.counter_descriptor_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent, _impl_.counters_),
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent, _impl_.gpu_id_),
    0,
    ~0u,
    1,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 12, -1, sizeof(::perfetto::protos::GpuCounterEvent_GpuCounter)},
        { 15, 26, -1, sizeof(::perfetto::protos::GpuCounterEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::perfetto::protos::_GpuCounterEvent_GpuCounter_default_instance_._instance,
    &::perfetto::protos::_GpuCounterEvent_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n1protos/perfetto/trace/gpu/gpu_counter_"
    "event.proto\022\017perfetto.protos\0323protos/per"
    "fetto/common/gpu_counter_descriptor.prot"
    "o\"\373\001\n\017GpuCounterEvent\022A\n\022counter_descrip"
    "tor\030\001 \001(\0132%.perfetto.protos.GpuCounterDe"
    "scriptor\022=\n\010counters\030\002 \003(\0132+.perfetto.pr"
    "otos.GpuCounterEvent.GpuCounter\022\016\n\006gpu_i"
    "d\030\003 \001(\005\032V\n\nGpuCounter\022\022\n\ncounter_id\030\001 \001("
    "\r\022\023\n\tint_value\030\002 \001(\003H\000\022\026\n\014double_value\030\003"
    " \001(\001H\000B\007\n\005value"
};
static const ::_pbi::DescriptorTable* const descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_deps[1] =
    {
        &::descriptor_table_protos_2fperfetto_2fcommon_2fgpu_5fcounter_5fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto = {
    false,
    false,
    375,
    descriptor_table_protodef_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto,
    "protos/perfetto/trace/gpu/gpu_counter_event.proto",
    &descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_once,
    descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto::offsets,
    file_level_metadata_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto,
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_getter() {
  return &descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto(&descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto);
namespace perfetto {
namespace protos {
// ===================================================================

class GpuCounterEvent_GpuCounter::_Internal {
 public:
  using HasBits = decltype(std::declval<GpuCounterEvent_GpuCounter>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(GpuCounterEvent_GpuCounter, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::perfetto::protos::GpuCounterEvent_GpuCounter, _impl_._oneof_case_);
  static void set_has_counter_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

GpuCounterEvent_GpuCounter::GpuCounterEvent_GpuCounter(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.GpuCounterEvent.GpuCounter)
}
GpuCounterEvent_GpuCounter::GpuCounterEvent_GpuCounter(const GpuCounterEvent_GpuCounter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GpuCounterEvent_GpuCounter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.counter_id_) {}

    , decltype(_impl_.value_){}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.counter_id_ = from._impl_.counter_id_;
  clear_has_value();
  switch (from.value_case()) {
    case kIntValue: {
      _this->_internal_set_int_value(from._internal_int_value());
      break;
    }
    case kDoubleValue: {
      _this->_internal_set_double_value(from._internal_double_value());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:perfetto.protos.GpuCounterEvent.GpuCounter)
}

inline void GpuCounterEvent_GpuCounter::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.counter_id_) { 0u }

    , decltype(_impl_.value_){}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_value();
}

GpuCounterEvent_GpuCounter::~GpuCounterEvent_GpuCounter() {
  // @@protoc_insertion_point(destructor:perfetto.protos.GpuCounterEvent.GpuCounter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GpuCounterEvent_GpuCounter::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_value()) {
    clear_value();
  }
}

void GpuCounterEvent_GpuCounter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GpuCounterEvent_GpuCounter::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:perfetto.protos.GpuCounterEvent.GpuCounter)
  switch (value_case()) {
    case kIntValue: {
      // No need to clear
      break;
    }
    case kDoubleValue: {
      // No need to clear
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}


void GpuCounterEvent_GpuCounter::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.GpuCounterEvent.GpuCounter)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.counter_id_ = 0u;
  clear_value();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GpuCounterEvent_GpuCounter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 counter_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_counter_id(&has_bits);
          _impl_.counter_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // int64 int_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _internal_set_int_value(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // double double_value = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 25)) {
          _internal_set_double_value(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* GpuCounterEvent_GpuCounter::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.GpuCounterEvent.GpuCounter)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 counter_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_counter_id(), target);
  }

  switch (value_case()) {
    case kIntValue: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteInt64ToArray(
          2, this->_internal_int_value(), target);
      break;
    }
    case kDoubleValue: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this->_internal_double_value(), target);
      break;
    }
    default: ;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.GpuCounterEvent.GpuCounter)
  return target;
}

::size_t GpuCounterEvent_GpuCounter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:perfetto.protos.GpuCounterEvent.GpuCounter)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional uint32 counter_id = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_counter_id());
  }

  switch (value_case()) {
    // int64 int_value = 2;
    case kIntValue: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_int_value());
      break;
    }
    // double double_value = 3;
    case kDoubleValue: {
      total_size += 9;
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GpuCounterEvent_GpuCounter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GpuCounterEvent_GpuCounter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GpuCounterEvent_GpuCounter::GetClassData() const { return &_class_data_; }


void GpuCounterEvent_GpuCounter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GpuCounterEvent_GpuCounter*>(&to_msg);
  auto& from = static_cast<const GpuCounterEvent_GpuCounter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.GpuCounterEvent.GpuCounter)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_counter_id(from._internal_counter_id());
  }
  switch (from.value_case()) {
    case kIntValue: {
      _this->_internal_set_int_value(from._internal_int_value());
      break;
    }
    case kDoubleValue: {
      _this->_internal_set_double_value(from._internal_double_value());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GpuCounterEvent_GpuCounter::CopyFrom(const GpuCounterEvent_GpuCounter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.GpuCounterEvent.GpuCounter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GpuCounterEvent_GpuCounter::IsInitialized() const {
  return true;
}

void GpuCounterEvent_GpuCounter::InternalSwap(GpuCounterEvent_GpuCounter* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);

  swap(_impl_.counter_id_, other->_impl_.counter_id_);
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata GpuCounterEvent_GpuCounter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_getter, &descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_once,
      file_level_metadata_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto[0]);
}
// ===================================================================

class GpuCounterEvent::_Internal {
 public:
  using HasBits = decltype(std::declval<GpuCounterEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(GpuCounterEvent, _impl_._has_bits_);
  static const ::perfetto::protos::GpuCounterDescriptor& counter_descriptor(const GpuCounterEvent* msg);
  static void set_has_counter_descriptor(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_gpu_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::perfetto::protos::GpuCounterDescriptor&
GpuCounterEvent::_Internal::counter_descriptor(const GpuCounterEvent* msg) {
  return *msg->_impl_.counter_descriptor_;
}
void GpuCounterEvent::clear_counter_descriptor() {
  if (_impl_.counter_descriptor_ != nullptr) _impl_.counter_descriptor_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
GpuCounterEvent::GpuCounterEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.GpuCounterEvent)
}
GpuCounterEvent::GpuCounterEvent(const GpuCounterEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GpuCounterEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.counters_){from._impl_.counters_}
    , decltype(_impl_.counter_descriptor_){nullptr}
    , decltype(_impl_.gpu_id_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.counter_descriptor_ = new ::perfetto::protos::GpuCounterDescriptor(*from._impl_.counter_descriptor_);
  }
  _this->_impl_.gpu_id_ = from._impl_.gpu_id_;
  // @@protoc_insertion_point(copy_constructor:perfetto.protos.GpuCounterEvent)
}

inline void GpuCounterEvent::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.counters_){arena}
    , decltype(_impl_.counter_descriptor_){nullptr}
    , decltype(_impl_.gpu_id_) { 0 }

  };
}

GpuCounterEvent::~GpuCounterEvent() {
  // @@protoc_insertion_point(destructor:perfetto.protos.GpuCounterEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GpuCounterEvent::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_counters()->~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.counter_descriptor_;
}

void GpuCounterEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GpuCounterEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.GpuCounterEvent)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_counters()->Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.counter_descriptor_ != nullptr);
    _impl_.counter_descriptor_->Clear();
  }
  _impl_.gpu_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GpuCounterEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .perfetto.protos.GpuCounterDescriptor counter_descriptor = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_counter_descriptor(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated .perfetto.protos.GpuCounterEvent.GpuCounter counters = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_counters(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 gpu_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _Internal::set_has_gpu_id(&has_bits);
          _impl_.gpu_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* GpuCounterEvent::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.GpuCounterEvent)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .perfetto.protos.GpuCounterDescriptor counter_descriptor = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::counter_descriptor(this),
        _Internal::counter_descriptor(this).GetCachedSize(), target, stream);
  }

  // repeated .perfetto.protos.GpuCounterEvent.GpuCounter counters = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_counters_size()); i < n; i++) {
    const auto& repfield = this->_internal_counters(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // optional int32 gpu_id = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        3, this->_internal_gpu_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.GpuCounterEvent)
  return target;
}

::size_t GpuCounterEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:perfetto.protos.GpuCounterEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .perfetto.protos.GpuCounterEvent.GpuCounter counters = 2;
  total_size += 1UL * this->_internal_counters_size();
  for (const auto& msg : this->_internal_counters()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .perfetto.protos.GpuCounterDescriptor counter_descriptor = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.counter_descriptor_);
    }

    // optional int32 gpu_id = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_gpu_id());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GpuCounterEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GpuCounterEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GpuCounterEvent::GetClassData() const { return &_class_data_; }


void GpuCounterEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GpuCounterEvent*>(&to_msg);
  auto& from = static_cast<const GpuCounterEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.GpuCounterEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_counters()->MergeFrom(from._internal_counters());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_counter_descriptor()->::perfetto::protos::GpuCounterDescriptor::MergeFrom(
          from._internal_counter_descriptor());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.gpu_id_ = from._impl_.gpu_id_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GpuCounterEvent::CopyFrom(const GpuCounterEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.GpuCounterEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GpuCounterEvent::IsInitialized() const {
  return true;
}

void GpuCounterEvent::InternalSwap(GpuCounterEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _internal_mutable_counters()->InternalSwap(other->_internal_mutable_counters());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GpuCounterEvent, _impl_.gpu_id_)
      + sizeof(GpuCounterEvent::_impl_.gpu_id_)
      - PROTOBUF_FIELD_OFFSET(GpuCounterEvent, _impl_.counter_descriptor_)>(
          reinterpret_cast<char*>(&_impl_.counter_descriptor_),
          reinterpret_cast<char*>(&other->_impl_.counter_descriptor_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GpuCounterEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_getter, &descriptor_table_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto_once,
      file_level_metadata_protos_2fperfetto_2ftrace_2fgpu_2fgpu_5fcounter_5fevent_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::perfetto::protos::GpuCounterEvent_GpuCounter*
Arena::CreateMaybeMessage< ::perfetto::protos::GpuCounterEvent_GpuCounter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::perfetto::protos::GpuCounterEvent_GpuCounter >(arena);
}
template<> PROTOBUF_NOINLINE ::perfetto::protos::GpuCounterEvent*
Arena::CreateMaybeMessage< ::perfetto::protos::GpuCounterEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::perfetto::protos::GpuCounterEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
