name: Build OSX binaries

on:
  - push
  - pull_request

jobs:
  osx:
    runs-on: macos-12
    steps:
      - run: brew install zmq sdl2 libelf protobuf meson ninja
      - uses: actions/checkout@v3
      - run: git clone https://github.com/pybind/pybind11.git
        working-directory: ext/orbetto
      - run: git clone https://github.com/puddly/ripyl.git
        working-directory: ext/orbetto
      - run: sudo pip3 install scipy
      - run: sudo pip3 install numpy
      - run: sudo pip3 install setuptools==45
      - run: python3 setup.py install
        working-directory: ext/orbetto/ripyl
      - run: meson setup ./build
        working-directory: ext/orbetto
      - run: ninja -C ./build
        working-directory: ext/orbetto
      - run: meson install -C ./build --destdir ./install
        working-directory: ext/orbetto
      - uses: actions/upload-artifact@v3
        with:
          name: orbetto-osx
          path: ext/orbetto/build/install/**/*
          if-no-files-found: error


