name: Build Linux binaries

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libusb-1.0-0-dev libzmq3-dev meson libsdl2-dev libdwarf-dev libdw-dev libelf-dev libcapstone-dev python3-pip ninja-build protobuf-compiler
      - run: sudo pip3 install meson==1.2.0
      - uses: actions/checkout@v3
      - run: git clone https://github.com/pybind/pybind11.git
        working-directory: ext/orbetto  
      - run: git clone https://github.com/puddly/ripyl.git # Ripyl is a Protocol Decoder Python Library
        working-directory: ext/orbetto
      - run: sudo pip3 install scipy  # Python dependency for Ripyl
      - run: sudo pip3 install numpy  # Python dependency for Ripyl
      - run: sudo pip3 install setuptools==45  # Ripyl needs setuptools 45 to install
      - run: python3 setup.py install # Install Ripyl
        working-directory: ext/orbetto/ripyl # in the source directory
      - run: sudo pip3 install pandas # Python dependency for fast data analysis
      - run: meson setup ./build
        working-directory: ext/orbetto
      - run: ninja -C ./build
        working-directory: ext/orbetto
      - run: meson install -C ./build --destdir ./install
        working-directory: ext/orbetto
      - uses: actions/upload-artifact@v3
        with:
          name: orbetto-linux
          path: ext/orbetto/build/install/**/*
          if-no-files-found: error


