name: "Publish to PyPI"
on:
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/emdbg
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install release tools
      run: |
        python -m pip install twine build
    - name: Package library
      run: |
        python -m build
        twine check dist/*

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

